parameters:
    locale: "en"

framework:
    test: ~
    translator: { fallback: "%locale%" }
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    default_locale: "%locale%"
