language: php

php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

before_script:
    - composer self-update
    - echo -e "<?php\n\nreturn '/contao/core';\n" > ./system/config/pathconfig.php
    - touch ./system/config/localconfig.php

install:
    - composer install --prefer-dist --dev

script:
    - ./vendor/bin/phpunit -c app/phpunit.xml.dist
